/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface KpwApp {
    /**
    * My Property
    * @type {string}
    * @memberof KPWAppElement
    */
    'text': string;
  }
  interface KpwCard {
    /**
    * Content property
    * @type {string}
    * @memberof KPWAppElement
    */
    'content': string;
    /**
    * Heading property
    * @type {string}
    * @memberof KPWCardElement
    */
    'heading': string;
    /**
    * Image URL Property
    * @type {string}
    * @memberof KPWCardElement
    */
    'imageUrl': string;
  }
  interface KpwHeader {}
  interface KpwProfile {
    'imageSrc': string;
    'name': string;
    'title': string;
    'url': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLKpwAppElement extends Components.KpwApp, HTMLStencilElement {}
  var HTMLKpwAppElement: {
    prototype: HTMLKpwAppElement;
    new (): HTMLKpwAppElement;
  };

  interface HTMLKpwCardElement extends Components.KpwCard, HTMLStencilElement {}
  var HTMLKpwCardElement: {
    prototype: HTMLKpwCardElement;
    new (): HTMLKpwCardElement;
  };

  interface HTMLKpwHeaderElement extends Components.KpwHeader, HTMLStencilElement {}
  var HTMLKpwHeaderElement: {
    prototype: HTMLKpwHeaderElement;
    new (): HTMLKpwHeaderElement;
  };

  interface HTMLKpwProfileElement extends Components.KpwProfile, HTMLStencilElement {}
  var HTMLKpwProfileElement: {
    prototype: HTMLKpwProfileElement;
    new (): HTMLKpwProfileElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'kpw-app': HTMLKpwAppElement;
    'kpw-card': HTMLKpwCardElement;
    'kpw-header': HTMLKpwHeaderElement;
    'kpw-profile': HTMLKpwProfileElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface KpwApp {
    /**
    * My Property
    * @type {string}
    * @memberof KPWAppElement
    */
    'text'?: string;
  }
  interface KpwCard {
    /**
    * Content property
    * @type {string}
    * @memberof KPWAppElement
    */
    'content'?: string;
    /**
    * Heading property
    * @type {string}
    * @memberof KPWCardElement
    */
    'heading'?: string;
    /**
    * Image URL Property
    * @type {string}
    * @memberof KPWCardElement
    */
    'imageUrl'?: string;
  }
  interface KpwHeader {}
  interface KpwProfile {
    'imageSrc'?: string;
    'name'?: string;
    'title'?: string;
    'url'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'kpw-app': KpwApp;
    'kpw-card': KpwCard;
    'kpw-header': KpwHeader;
    'kpw-profile': KpwProfile;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'kpw-app': LocalJSX.KpwApp & JSXBase.HTMLAttributes<HTMLKpwAppElement>;
      'kpw-card': LocalJSX.KpwCard & JSXBase.HTMLAttributes<HTMLKpwCardElement>;
      'kpw-header': LocalJSX.KpwHeader & JSXBase.HTMLAttributes<HTMLKpwHeaderElement>;
      'kpw-profile': LocalJSX.KpwProfile & JSXBase.HTMLAttributes<HTMLKpwProfileElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


