/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface KpwCard {
    'content': string;
    'heading': string;
    'imageUrl': string;
  }
  interface KpwContainer {}
  interface KpwHeader {}
  interface KpwProfile {
    'imageSrc': string;
    'name': string;
    'position': string;
    'url': string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
}

declare global {


  interface HTMLKpwCardElement extends Components.KpwCard, HTMLStencilElement {}
  var HTMLKpwCardElement: {
    prototype: HTMLKpwCardElement;
    new (): HTMLKpwCardElement;
  };

  interface HTMLKpwContainerElement extends Components.KpwContainer, HTMLStencilElement {}
  var HTMLKpwContainerElement: {
    prototype: HTMLKpwContainerElement;
    new (): HTMLKpwContainerElement;
  };

  interface HTMLKpwHeaderElement extends Components.KpwHeader, HTMLStencilElement {}
  var HTMLKpwHeaderElement: {
    prototype: HTMLKpwHeaderElement;
    new (): HTMLKpwHeaderElement;
  };

  interface HTMLKpwProfileElement extends Components.KpwProfile, HTMLStencilElement {}
  var HTMLKpwProfileElement: {
    prototype: HTMLKpwProfileElement;
    new (): HTMLKpwProfileElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };
  interface HTMLElementTagNameMap {
    'kpw-card': HTMLKpwCardElement;
    'kpw-container': HTMLKpwContainerElement;
    'kpw-header': HTMLKpwHeaderElement;
    'kpw-profile': HTMLKpwProfileElement;
    'my-component': HTMLMyComponentElement;
  }
}

declare namespace LocalJSX {
  interface KpwCard {
    'content'?: string;
    'heading'?: string;
    'imageUrl'?: string;
  }
  interface KpwContainer {}
  interface KpwHeader {}
  interface KpwProfile {
    'imageSrc'?: string;
    'name'?: string;
    'position'?: string;
    'url'?: string;
  }
  interface MyComponent {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }

  interface IntrinsicElements {
    'kpw-card': KpwCard;
    'kpw-container': KpwContainer;
    'kpw-header': KpwHeader;
    'kpw-profile': KpwProfile;
    'my-component': MyComponent;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'kpw-card': LocalJSX.KpwCard & JSXBase.HTMLAttributes<HTMLKpwCardElement>;
      'kpw-container': LocalJSX.KpwContainer & JSXBase.HTMLAttributes<HTMLKpwContainerElement>;
      'kpw-header': LocalJSX.KpwHeader & JSXBase.HTMLAttributes<HTMLKpwHeaderElement>;
      'kpw-profile': LocalJSX.KpwProfile & JSXBase.HTMLAttributes<HTMLKpwProfileElement>;
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
    }
  }
}


